sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  jwt:
    admin-secret-key: itcastLearningJavaWebProjectWhichNameIsSkyTakeOut
    admin-ttl: 86_400_000
    admin-token-name: token
    user-secret-key: itheimaLearningJavaWebProjectWhichNameIsSkyTakeOut
    user-ttl: 86_400_000
    user-token-name: authentication
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: web-yizhe-sky
  redis:
    host: localhost
    port: 6379
    database: 1
    password: 123456
  wechat:
    appid: wxa7ed9aee4e5d54a6
    secret: e5ef5d59fa9affcede7e44e371ac50bf
  shop:
    address: 沈阳浑南区白塔堡美食一街 256 号
  baidu:
    ak: UnableToAccessBaiduMapAPI